
volumes:
  v-mysql:
    driver: local
    driver_opts:
      type: "none"
      device: "./mysql/data"
      o: "bind"
  v-app:
    driver: local
    driver_opts:
      type: "none"
      device: "./app/data"
      o: "bind"

networks:
  spring-network:
    name: spring-network

services:
  mysqldb:
    container_name: "spring_db"
    image: spring/mysqldb:study
    build: ./mysql
    env_file: ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "0.0.0.0:3306:3306"
    networks:
      - spring-network
    volumes:
      - v-mysql:/var/lib/mysql

  spring:
    container_name: "spring_app"
    image: spring/app:study
    build: ./app
    ports:
      - "0.0.0.0:8000:8000"
    env_file: ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysqldb
    networks:
      - spring-network
    volumes:
      - v-app:/app
